name: make_image
on:
  push:
    tags:
      - '*'
jobs:
  make_image:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          docker build . --tag ghcr.io/${{ github.repo }}:latest
          docker push ghcr.io/${{ github.repo }}:latest


